### ISSUE TITLE
Fixing Word Schedule

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#112]
Currently, the BasicSR is too punishing when a user gets a word wrong towards the end of the learning "cycle". If at the 3rd repetition of a word the user gets it wrong, it goes back to stage "0" where the user needs to see it again 4 times before "learning" it. 

There is also a "bug", where if the time to practice is the at `2024-01-24 11:30` and the user performs the exercise at `2024-01-24 10:30` then that exercise does not count towards correctly remembering the word. Instead the user keeps getting this word as an exercise until after 11:30 where then the status is updated. (Unless they get it incorrect, and that resets the scheduled time). 

**Word Scheduling Procedure**: Currently, if at some point there are not enough bookmarks for 10 exercises, we add some new words to the schedule. This is OK, but the words that are picked for the exercise is given at random. Since, the user resets progress in the learning words if they get it wrong before learning them, this can create cases where the user never gets to learn a word (since the list of scheduled words might be too extensive). By randomizing the words that are shown, we run the risk that the user never completes 4 correct in a row for a particular word.

My Suggestions:

1. Instead of resetting the word to 0, instead move the word schedule down 1 level. This matches the Leitner System as shown below. We can consider a word learned if it gets correctly recalled after 16 days + 3 consecutive correct answers? We could also allow a chance to "recover" the streak, by rescheduling the word to the same day, and if they get it correct, then the schedule is kept the same as before. Let me know what you think.
![image](https://github.com/zeeguu/api/assets/17390076/aad5db8b-6776-42aa-8f08-572d6f7992ad)
2. Update the schedule recall time if current date (not including time) is equal or below to the scheduled date. This should avoid situations where the user seems the same word multiple times, while ensuring the schedule is followed. 
3. Scheduling Procedure, I would say we should randomize (so the exercises are not given in the same order), but we should prioritize words that are close to being learned. Essentially, ensuring a sort of "FIFO" to allow old words to slowly phase out and being learned, while newer ones are given once the older ones are recalled.  This might also be something we see that with fixing the schedule bug might happen less.

**Comment by mircealungu** [comment]
Regarding your suggestions @tfnribeiro: 
1. sounds good
2. i don't see this being a very big problem - that we consider a day 24h or calendar date should not matter much; but it's true that it should be used consistently in the app; from your description it seems that we schedule based on calendar date, but we update status based on multiples of 24h from creation? 
3. YES. Indeed, from the words that are to be rehearsed at the current moment, I'd say we should prioritize
   - the ones closer to learning as you suggest
   - among those, the ones with higher frequency in the language (fast-tracking frequently used words)
