### ISSUE TITLE
Make 'Render ARchitectural Diff with ArchLens' Optional?

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#183]
We currently always get any PR in this repo marked as if it occurred an error due to the Workflow: [Render ARchitectural Diff with ArchLens](https://github.com/zeeguu/api/actions/workflows/render-architectural-diff.yml)

Could we make this optional, so that we can see when we are failing some of the Unit tests, rather than having to double check if the Unit tests do complete?

**Comment by mircealungu** [comment]
Thanks for pushing me on this.
I finally looked into why the Archness Diff Render was failing and as far as I can tell I've fixed it. 
It seems that our tests are failing though?
