### ISSUE TITLE
"<1 hour ago" seems a bit disingenuous when I just left the article

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#189]
i just left the article:

<img width="1008" alt="image" src="https://github.com/user-attachments/assets/5b7730e1-b136-489d-92bd-82e84b7f32fd">

the fact that the text says: "<1 hour ago" is strange. it should know that i've just left that article "just now". 

either we introduce "a few moments ago" (for up to a few minutes) or maybe we just don't say anything for less than 10 minutes?

**Comment by tfnribeiro** [comment]
We could just do minutes up to an hour and then hours with "about 1, 2 hour ago ..."

What do you think? Maybe I should also do days?

**Comment by mircealungu** [comment]
yes. sounds good.

**Comment by mircealungu** [comment]
the other nit to pick here is that the rendering of readable time might have been better fit as a front-end rather than a back-end task. but that's really nitpicking :)))

though I think we might already use a readable time library somewhere else in the front-end?

**Comment by tfnribeiro** [comment]
Alright, I have put it in the frontend, so now the backend only sends in the minutes, so the frontend can do the conversion / decide how to display it:

What I am ending up with is "just now" up until 10 minutes, then you see minutes, like this:

![image](https://github.com/user-attachments/assets/03eaf000-44ac-4381-a005-f5cabcea45c3)

And then with hours and days is: "about 1 hour ago" or "about 1 day ago"

**Comment by mircealungu** [comment]
Looks good!
