### ISSUE TITLE
Add Profanity Filter to Random Words

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#197]
- Add a simple profanity filter to avoid getting "inappropriate" words from the SimilarWords API.

**Comment by tfnribeiro** [comment]
Consider using the following library: https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words?tab=readme-ov-file

**Comment by mircealungu** [comment]
We should!

**Comment by tfnribeiro** [comment]
I found some word lists and plugging it in results in about 2.8k words being removed, some of those could be okay, but I guess in this case we will still have plenty of "valid" words to work as distractors, and we avoid the cases where a "London" or "December" come in.

**Comment by mircealungu** [comment]
We can afford to remove 2.8k words, for sure :)

**Comment by tfnribeiro** [comment]
@mircealungu I was looking back at this, and I think I can make a PR, I am just not sure how we want to handle the external repositories. I cloned to repositories, and I am not sure if they should be included in our Repo, but instead just have a reference to the repo we used?

**Comment by mircealungu** [comment]
ah. so you use two file lists from two different repos? 
add them to a /data folder and add a .md that specifies their source?
