### ISSUE TITLE
Students invisible when joining second classroom

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#198]
As reported by one of our teachers: 

> Last year, our colleague CL, teacher German has started with Zeeguu too. Some students follow both French and German classes. The students who first had an account in French class and then added German, were transferred to the German class in Zeeguu and get deleted/lost (I do not see them anymore, nor their read articles) in the French.

**Comment by mircealungu** [comment]
I guess we have to allow a student to belong to multiple classes at the same time. 

Indeed, a student can only belong to a single class at the moment, and this means that when they join the german class, they don't belong to the french one, so this is why the french teacher can't see them anymore.

**Comment by igawaclawska** [comment]
I will look into adapting the UI and front end of the Onboarding steps and Settings so that they support multiple classrooms

**Comment by mircealungu** [comment]
Cool. Tak to both!

@iga: onboarding can stay the same. Settings will need to be adapted indeed!

**Comment by tfnribeiro** [comment]
I have done some work on this and I believe that the backend is set-up to allow multiple classes.

@igawaclawska: Some of the data will change from the backend (we used to expect 1 int ID and now we will get an array), so maybe I will make sure to update all the endpoints in the frontend and then you could do the UI to display/remove the classes - this will be next week though. Need to slowly go through all to make sure nothing is missed.

**Comment by igawaclawska** [comment]
> @igawaclawska: Some of the data will change from the backend (we used to expect 1 int ID and now we will get an array), so maybe I will make sure to update all the endpoints in the frontend and then you could do the UI to display/remove the classes - this will be next week though. Need to slowly go through all to make sure nothing is missed.

@tfnribeiro: ✅ Okok. I can start by mocking up some variants of it in Figma, and then once the endpoints are ready -implementing the one we like most.

**Comment by tfnribeiro** [comment]
Okay, I feel like I have the functionality working here is the POV of a student:


https://github.com/user-attachments/assets/f1f4a903-9b4c-4365-befa-2b44d6f6408e

If a code is invalid:

**Comment by igawaclawska** [comment]
I'm currently also collecting some considerations related to multiple classroom support. I will post them in a bit.

**Comment by igawaclawska** [comment]
Currently, it seems that students are able to view content from all classrooms at once. What are your thoughts on allowing a student to be part of multiple classrooms but only have one active at a time? This could solve the issues with translation language confusion (and perhaps with exercise generation).

**Comment by igawaclawska** [comment]
Another question -  how are exercises generated in the classroom setting? Are they based on the content provided by teachers that students translated, or are they generated based on both Zeeguu recommendations and texts from the teachers that students translated?

**Comment by tfnribeiro** [comment]
The active class could work, but again - if that's done through the settings it might be a bit annoying to navigate 3 screens to change back and forth. But for now I think it could be the way to go so the functionality "looks" the same as before essentially. 

The exercises are just based on the translated words, the classroom feature allows the Teachers to see if the students are reading/doing exercises and to manually share texts to the students, but this might not be used as much. 

So in their dashboards teachers can see what words they have translated/how much time they have spent reading e.g.

![image](https://github.com/user-attachments/assets/376f5618-69f4-4e67-a912-0ae4bf7af855)

![image](https://github.com/user-attachments/assets/2a92a237-78f3-4074-921a-84779ab944f2)

**Comment by igawaclawska** [comment]
> The active class could work, but again - if that's done through the settings it might be a bit annoying to navigate 3 screens to change back and forth. But for now I think it could be the way to go so the functionality "looks" the same as before essentially.

The "Current/active class" option, besides settings, could also be added as, for instance, a dropdown on the side navigation or on the homepage - underneath the Classroom tab

**Comment by tfnribeiro** [comment]
That's a good idea!

**Comment by igawaclawska** [comment]
What happens from the teacher's point of view when a student leaves a classroom and then re-enters it? I know that if students leave a classroom, their progress is not visible to the teacher. What happens if they re-enter? Will their progress, exercises done, and translated words be reset to zero or preserved?
