### ISSUE TITLE
When going to Word History the data is not up to date

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#199]
The data displayed in Word History Tab is not accurately reflecting the state of the database. Namely, if a user translates an article and then goes to the page the data won't be present there.

**Comment by tfnribeiro** [comment]
I haven't really been able to reproduce this, so it's likely not due to time, but maybe number of transactions that causes the reads to go stale?

Some of the possible solutions suggested closing the Sessions after they are used, so maybe we can try to see if that makes a difference in this case.

**Comment by mircealungu** [comment]
This should be even easier to test then. Just hit the test DB with a lot of read and write requests and see whether after a certain number they go stale!

**Comment by mircealungu** [comment]
In fact, creating a synthetic workload that we can hit the API with might be cool also for performance testing -- seeing how the API scales when we hit it with 1000 connections at the same time, etc.

**Comment by tfnribeiro** [comment]
Sure, I think that sounds like a good idea - but how would you simulate this - would it be a front end script that makes a bunch of API async calls? 

Currently, I am inserting all the bookmarks in the DB for 2 test users and see if after that I have any issues.

**Comment by tfnribeiro** [comment]
I have tried inserting 200k Bookmarks and spamming the API from the Frontend inserting values in the user activity table, but still the history seems OK to me. I am a bit unsure what else I could try, if anything I think this was more intense than what our server is doing. 

Is there any other setting that sets Flask to "production" or something  that might not be activated in the dev environment?

**Comment by mircealungu** [comment]
> Sure, I think that sounds like a good idea - but how would you simulate this - would it be a front end script that makes a bunch of API async calls?

yes. a script that hits the API endpoints in some kind of meaningful scenario replicating user behavior. i was thinking more as python than as frontend. 

> 
> Currently, I am inserting all the bookmarks in the DB for 2 test users and see if after that I have any issues.

**Comment by mircealungu** [comment]
> I have tried inserting 200k Bookmarks and spamming the API from the Frontend inserting values in the user activity table, but still the history seems OK to me. I am a bit unsure what else I could try, if anything I think this was more intense than what our server is doing.

how did you insert the 200k bookmarks?
i think we should really try so simulate a client sending api requests. 
my suspicion is that it has to go through the API for the problem to be revealed.
we are using this Flask-SQLAlchemy extra layer that does it's own tricks with transactions, that i never managed to look attentively into. Problem might be there.

> 
> Is there any other setting that sets Flask to "production" or something that might not be activated in the dev environment?

not that i'm aware of. 
this is the only config param that i'm seeing that might be related

# Required by API
DEBUG=False


> 
> I will also say that I can easily see this behaviour in the API - just by translating a word, it never comes up in the history - so one would think it wouldn't be as difficult to reproduce!

**Comment by mircealungu** [comment]
So again, a python app that does the following:
- login a user
- get a translation
- wait a minute
- get the history
- check that the translation is in there
- until this last condition does not hold would be the simplest test script then

Alternatively, maybe the problem is only in production and not in debug.so try to change your config locally to debug false?

**Comment by tfnribeiro** [comment]
I can set up the python application to work as a client, but the translations will just be a random string (as I don't have API access to google, and it wouldn't make sense to use our budget in this situations. 

I will try with the debug=FALSE

**Comment by mircealungu** [comment]
YES. Random strings are fine!

**Comment by tfnribeiro** [comment]
Okay - so I managed to get it to fail - not while running, but essentially I wrote the script and let it run and hibernated the computer when closing off yesterday.

Today, when re-logging the issue is present - which makes me thing, could it be related with the session idling in some way?

I will have the script running this morning with 3 different accounts and see if it occurs under normal use, but this is at least something!

**Comment by mircealungu** [comment]
Yes. That's the beginning of the end for this bug! :)

**Comment by mircealungu** [comment]
I have the feeling that we will have to understand [this discussion](https://stackoverflow.com/questions/51446322/flask-sqlalchemy-set-expire-on-commit-false-only-for-current-session) because it might be relevant for us.

**Comment by tfnribeiro** [comment]
I see - I am not sure I fully get it, as I haven't set up the Session and Model, but I also notice that after opening a connection it doesn't seem it gets closed up until the user signs out - by looking at the process lists, it can quickly grow with all the connections being left on sleep:

![image](https://github.com/user-attachments/assets/f87b0f9e-d258-4af8-9c87-adaee8750179)

I also try to replicate it by just hibernating and resuming the computer but that isn't enough so the time it's in Hibernation did also have an impact.

**Comment by mircealungu** [comment]
those are the connections to the DB? how do you show them?

**Comment by tfnribeiro** [comment]
Run the following query: `show full processlist;`

**Comment by mircealungu** [comment]
alternative hypothesis is that it might block if we don't call the API for a long period, e.g. 2h? 
in the sense of, maybe if we call it every minute it never goes stale? 
but still, i think it's worth calling it many times first, to see whether that results in the stale data.

**Comment by tfnribeiro** [comment]
I haven't been able to get it to get stale date - with about 1000 calls. 

Also update, hibernating for 30ish minutes did not cause the error. So it might be a long timeout associated - Though this wouldn't really explain why a new connection would come in and fail to retrieve the data. So maybe it might be after a certain number of transaction ?

**Comment by tfnribeiro** [comment]
Last week, I left once again 3 scripts adding bookmarks and checking they are retrieved in history, but this time only 2 of them failed, while one is still running.

I guess so far the following as been observed:
- The number of insertions doesn't seem to be the main reason. The last time it failed it was with around 800 insertions and now it was with about 900 (491 in each process that failed)
- It only seems to happen after I hibernate for a long time, but today it seems that is not the only condition (as one of the processes is still running OK. I checked MySQL timeouts and they seem to be around 8H, this would match with the first time it occurred.
- After the error occurs, then I can no longer see the bookmarks of newly translated words, in the frontend - which mirrors what we see in Production. Restarting the SQL seems to fix it as it does in Production.
