### ISSUE TITLE
Setting a threshold for the Notifications

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#209]
When changing the notifications - it was a bit hard to estimate if I should have a threshold, but now that I got the email and took a look I have the following situation:

![image](https://github.com/user-attachments/assets/41026043-831a-47be-acd5-968ca5115962)

The article with the frog essentially has the word computer once, to describe that the researchers did some simulations. So I am thinking about setting maybe a threshold of 2 (which roughly means it would have to contain the keyword twice) to be relevant in this page.

What do you think ?

**Comment by mircealungu** [comment]
haha. on the bright side I got the chance to look at **at skrumpe** = _to shrink_. But besides this benefit, I agree that the frog article does not belong :)

**Comment by tfnribeiro** [comment]
Ahahha - yes! 

It will be hard to find a good threshold, but I think 2 might be enough to avoid the worst offenders let's say. My only worry is that we could have situations where the page would be almost empty with no articles, and maybe that isn't great either...
