### ISSUE TITLE
A bit more info in the notification emails

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#214]
Email notifications with included article titles are cool!

<img width="731" alt="image" src="https://github.com/user-attachments/assets/f2bfd53e-a19f-4206-827c-eae7e907607f">

One thing that we see above is that the same topic appears in two articles. 
I guess it would be nice if we showed the respective: sources, difficulty ratings, and lengths? 
It would better distinguish the two, and show the learner that they have options!

**Comment by mircealungu** [comment]
Possible formatting: 

```
kina
====

+ Slut med at gå på pension som 50-årig: Kina hæver pensionsalderen. 
  B1 - 2min - dr.dk

+ Kina hæver pensionsalderen til 58 år for kvinder og 63 år for mænd.
  A2 - 4min - politiken.dk

```

**Comment by tfnribeiro** [comment]
I actually think I don't mind the Read repetition, I think it also makes you look at the source link so you know where you will go to. 

But with the title I was actually thinking that it might be nice to just use an h3 or similar, e.g.

### Kina

___

Slut med at gå på pension som 50-årig: Kina hæver pensionsalderen (2min, B1)
[read](https://www.dr.dk/nyheder/udland/slut-med-gaa-paa-pension-som-50-aarig-kina-haever-pensionsalderen) on dr.dk

Kina hæver pensionsalderen til 58 år for kvinder og 63 år for mænd (4min, A2)
[read](https://politiken.dk/internationalt/art10068847/Kina-h%C3%A6ver-pensionsalderen-til-58-%C3%A5r-for-kvinder-og-63-%C3%A5r-for-m%C3%A6nd) on politiken.dk

**Comment by mircealungu** [comment]
I like the H3 idea for the subject!

**Comment by mircealungu** [comment]
and with H3, metadata on the second row, and bold title? 

### Kina

**Slut med at gå på pension som 50-årig: Kina hæver pensionsalderen** 
&nbsp;&nbsp; 2min, B1, [read](https://www.dr.dk/nyheder/udland/slut-med-gaa-paa-pension-som-50-aarig-kina-haever-pensionsalderen) on dr.dk

**Kina hæver pensionsalderen til 58 år for kvinder og 63 år for mænd** 
&nbsp;&nbsp; 4min, A2, [read](https://politiken.dk/internationalt/art10068847/Kina-h%C3%A6ver-pensionsalderen-til-58-%C3%A5r-for-kvinder-og-63-%C3%A5r-for-m%C3%A6nd) on politiken.dk

**Comment by mircealungu** [comment]
Less is more? :)

**Comment by mircealungu** [comment]
Note, the abusing of `&nbsp;&nbsp;` to indent the metadata :)

**Comment by tfnribeiro** [comment]
Something like this? 

The HTML doesn't read the paragraphs as it does in python, but the articles should be the same:

![image](https://github.com/user-attachments/assets/2a7dc506-2b29-4fdd-ba3a-629408662fba)
