### ISSUE TITLE
Dev Mock Translations Support

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#232]
I have a branch that I use to allow to get translations into the Dev system which is useful to test new accounts and exercises if a user doesn't have any bookmarks yet. Is this something we want to merge into the main branch?

It works by adding an environment variable `DEV_SKIP_TRANSLATION: 1`, and it's check at the time of providing a translation to instead return the mock translation.

**Comment by mircealungu** [comment]
Yes, let's! That's very useful for anybody that wants to do development!
