### ISSUE TITLE
merge two onboarding steps in one...

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#235]
I'm creating a new test user and I realized that these two steps can be merged into one with no loss of functionality: 

<img width="894" alt="image" src="https://github.com/user-attachments/assets/22ef8c66-77d3-4279-af1c-cc4ac6759129">

<img width="896" alt="image" src="https://github.com/user-attachments/assets/14d59a21-bbb8-4966-82f2-6acb928e27f5">

should be fast to do and probably if you move the title from the first to the second nothing is lost, but rather the user has a better understanding of what's the plan, because of the example: 

<img width="692" alt="image" src="https://github.com/user-attachments/assets/65accb5d-daea-4e08-aba7-b33f71ba0358">

**Comment by tfnribeiro** [comment]
Isn't this an Web issue?

**Comment by igawaclawska** [comment]
> Isn't this an Web issue?

Yes, it's on the front-end

**Comment by igawaclawska** [comment]
I'll make an issue on the front-end repo

**Comment by tfnribeiro** [comment]
Closing as per above.

**Comment by mircealungu** [comment]
tak @tfnribeiro and @igawaclawsk! 
I was tired yesterday :)
