### ISSUE TITLE
Exercises are slow to Render due to high number of bookmarks

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#263]
When we changed the scheduled bookmarks, I didn't look too much into the performance of the `top_bookmarks_to_study` but I was testing a user with about 1900 total bookmarks, and it takes around 30 seconds for us to render the first exercise in the web, which made me wonder what are the total number of "fit to study" bookmarks we are working with. 

![{654FBCDC-77FE-4DB4-AB0A-139BE25FB0AC}](https://github.com/user-attachments/assets/09242bad-091a-4d0b-b792-b339d96c3439)

It does seem that our average user has 105 bookmarks, but there is quite a few (> 300) that have more than 200 bookmarks. 

This makes me think that it might be better to limit the query and order it already from the database, rather than doing it in python. I would expect that to improve the speed of the query overall.

**Comment by mircealungu** [comment]
Doing everything in the DB and also adding indexes if needed should definitely be the way to go :)

**Comment by tfnribeiro** [comment]
Yes, I will look into it - I will try to write the query in SQLAlchemy and see how it improves the query speed,

**Comment by mircealungu** [comment]
one order of magnitude improvement. nobody can complain about that :)
