### ISSUE TITLE
why can't we parse this article? 

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#285]
https://journalisten.dk/7-ud-af-10-af-os-arbejder-i-storrumskontor-og-rigtig-mange-hader-det/

i tried to read it with the extension, the waiting animation is very long

<img width="1290" alt="image" src="https://github.com/user-attachments/assets/e5282a0a-1ee9-451d-a40a-4de3ecf79f50">

followed by

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/4cfb253b-f21e-4da2-81df-d57af0f48b12">

**Comment by tfnribeiro** [comment]
There seems to be something wrong with the find_or_create_article:

![image](https://github.com/user-attachments/assets/4a422224-db07-45b7-a741-ab9b3c9aaf4f)
