### ISSUE TITLE
Add Spanish sources 

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#289]
We are currently only crawling one source with very few articles for Spanish.

**Comment by tfnribeiro** [comment]
I have done some investigation and I would propose the following sources:
 
- https://www.muyinteresante.com/feed/ - Science / Technology
- https://www.20minutos.es/rss/ - General News
- https://www.vogue.es/feed/rss - Fashion
- https://viajar.elperiodico.com/ - Traveling Magasine
- https://historia.nationalgeographic.com.es/feeds/rss - National Geographic (History)
- https://www.ngenespanol.com/feed/ - National Geographic (general)
- https://www.fotogramas.es/rss/default.xml - Culture (Movies & Series) 

I think this will already give some nice variety to the articles in Spanish.

Crawling them today I got the following:

**Total: 404 articles**

![image](https://github.com/user-attachments/assets/c43e7909-13b0-419b-9ac8-986f3e5257e1)

Seems we have a bit of everything topic wise:

![image](https://github.com/user-attachments/assets/75c33e29-76f4-4e5e-acc5-15f954754105)

**Comment by mircealungu** [comment]
and seems that 20minutes is doing the heavy lifting too!
