### ISSUE TITLE
PWA Notification Endpoint(s)

### ISSUE THREAD

**Issue by Sprangle** [zeeguu/api#295]
I need an endpoint that can be used for sending the user specific notifications.

@mircealungu and I discussed the possibility for a secondary endpoint that only fetches if the user actually clicks on the notification which could log data such as notificationId, user session ID and timestamp.

Here is my current PR:
https://github.com/zeeguu/web/pull/601

I currently use my own mock data via. a json file:
[
  {
    "message": "Mock data notification: Remember to complete your daily exercises!",
    "notificationId": "123",
    "url": "/exercises"
  },
  {
    "message": "Mock data notification: Find today's interesting article!",
    "notificationId": "123",
    "url": "/articles"
  },
  {
    "message": "Mock data notification: Remember to practice your recently learned words!",
    "notificationId": "123",
    "url": "/words"
  },
  {
    "message": "Mock data notification: Take a look at your history with Zeeguu!",
    "notificationId": "123",
    "url": "/history"
  }
]

**Comment by tfnribeiro** [comment]
Would this be best to implement via a new table @mircealungu ?

**Comment by tfnribeiro** [comment]
Note: The application should send a notification id with the message and the url it should take, the sw makes sure you can send the notification before asking.

**Comment by tfnribeiro** [comment]
This has been implemented in: https://github.com/zeeguu/api/pull/311
