### ISSUE TITLE
Update Report to Show Topic Origins

### ISSUE THREAD

**Issue by tfnribeiro** [zeeguu/api#296]
Currently, we have no good way of tracking how many of our topics are inferred or assigned topics based on the URLs. 

To fix this, I added a different color based on the source of the Topics of our articles:

| Before | After |
| :-: | :-: |
| ![image](https://github.com/user-attachments/assets/f8c68c26-4130-462c-8507-b1f08449e116) |  ![image](https://github.com/user-attachments/assets/16d2f426-5a1e-45a4-916a-321a1fccbc31)  | 
|     | ![image](https://github.com/user-attachments/assets/44051c16-80d3-4a56-a822-3c31d6293bdf) |

**Comment by mircealungu** [comment]
Super cool!
