### ISSUE TITLE
Contextual translations are sometimes broken

### ISSUE THREAD

**Issue by mircealungu** [zeeguu/api#315]
Sometimes the translations are stupidly broken, e.g. 

![image](https://github.com/user-attachments/assets/5dacc327-04e8-46e6-95cc-240a89003b32)

The culprit, in this particular case, seems to be the way we are delimiting the word to be translated in the query that we are sending to the translator. 

```
Det er der faktisk en simpel <span>for</span>mel for.
```

In this particular case, the problem bug seems to be in `TranslationQuery.for_word_occurrence` where we do a string search instead of tokenizing the context first. 

However, tokenization would solve a bit of the problem but not all of it: if the same word appears twice in the context, it's not clear which of the two we refer to. The `for_word_occurrence` accepts a parameter which is supposed to clarify which occurrence of the word in the sentence does one refer to but at the moment, the frontend does not send that information and the DB does not model it. 

How should we model to which occurrence are we referring to? There are two possibilities: 
1. track the index of appearance of the word in the sentence (e.g. the `for` we are interested in translating above is at index 0, meaning it's the first token ). This requires I think, ensuring that the tokenizer on the front-end that decides the index in the sentence of the given word is aligned with the tokenizer on the backend. 
2. track the alignment of the desired word in the sentence (e.g. the `for` we are interested in above is at position 29, 0-indexed). 

Note: Any of these two would also pave the way for highlighting past translations in a given text on re-opening.

**Comment by tfnribeiro** [comment]
When testing the levels in the frontend I encountered the issue, I mentioned with multiple occurrences of the same word in exercises:

![{21EF3E94-C199-48CA-A828-327804F296BD}](https://github.com/user-attachments/assets/32993444-a602-4e94-8699-26afe40a3ed5)

**Comment by mircealungu** [comment]
Aiii iaaa! Is your exercise example another kind of context that is not fit for study?

Even if we had alignment, the user would still not know which of the two is he supposed to click on.

**Comment by mircealungu** [comment]
With the [fix](https://github.com/zeeguu/python-translators/pull/66) in python-translators, the situation that raised this issue is fixed:

<img width="869" alt="image" src="https://github.com/user-attachments/assets/d544f5d8-0ff7-46ca-88f0-65a525e3762f" />

I think we can close this issue, and open another one for _saving the offset of a bookmark_ in a context.

**Comment by tfnribeiro** [comment]
Let's close this one then.

Regarding the exercises, I think it's fine that they are but if we detect they are the same word we shouldn't show the translation box above the word - it should just show correct and hide it
