### ISSUE TITLE
Text sources

### ISSUE THREAD

**Issue by SaraTolstrupHusum** [zeeguu/api#78]
Spanish only has higher level sources.
German only have one source for texts. (Frankfurter Allgemeine)

More sources are needed.

**Comment by SaraTolstrupHusum** [comment]
@mircealungu
KU teachers ask (in meeting today) if more Danish sources could be included. They suggested the following:

- Se & Hør (tabloid - maybe difficult to crawl??? https://www.seoghoer.dk/ )
- Verdens bedste nyheder (https://verdensbedstenyheder.dk/)
- Universitetsavisen (https://uniavisen.dk/)
- Atlas magasin (https://atlasmag.dk/)
- Magasinet 360 (https://magasinet360.dk/)

**Comment by mircealungu** [comment]
Added:
* ~~Atlas magasin (https://atlasmag.dk/)~~

The rest don't have RSS feeds:
* Se & Hør (tabloid - maybe difficult to crawl??? https://www.seoghoer.dk/ )
* Verdens bedste nyheder (https://verdensbedstenyheder.dk/)
* Universitetsavisen (https://uniavisen.dk/)
* Magasinet 360 (https://magasinet360.dk/)
